# Generated by Django 5.2.3 on 2025-08-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_category_feedback_dishes_cart_cartitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
