# Generated by Django 5.2.3 on 2025-09-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_order_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='dishes',
            field=models.ManyToManyField(related_name='feedbacks', to='restaurant.dish'),
        ),
    ]
